# lto.cmake — per-target LTO + linker
#
# Defaults (override with -D<PREFIX>_LTO_MODE=… and -D<PREFIX>_LINKER_CHOICE=…):
#   PERFORMANCE + non-Debug  → LTO_MODE auto (Clang GNU driver: ThinLTO; GCC/MSVC: IPO)
#   SUPPORT or Debug         → LTO off
#   Linker default           → best available: LTO on prefers lld→mold→gold (Clang); off prefers mold→gold→lld
#
# Modes: off | thin | full | ipo | auto
# Linker: default | lld | mold | gold | lld-link
#
# Usage: include(lto) → xsigma_lto_compute_default → cache *_LTO_MODE → add_library →
#        xsigma_target_apply_lto → xsigma_find_linker
#
# xsigma_print_lto_linker_summary(<PREFIX>)
#   Prints LTO mode and linker choice (and auto→thin/ipo hint) for module summaries.
# =============================================================================
include_guard(GLOBAL)
include(CheckIPOSupported)
include(CheckCXXCompilerFlag)

function(_xsigma_msvc_link out)
  set(_v FALSE)
  if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
      set(_v TRUE)
    elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
      if(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "MSVC")
        set(_v TRUE)
      elseif(CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "" AND CMAKE_CXX_COMPILER MATCHES
                                                                 "clang-cl"
      )
        set(_v TRUE)
      endif()
    endif()
  endif()
  set(${out} "${_v}" PARENT_SCOPE)
endfunction()

# First matching linker from candidate executable names.
function(_xsigma_first_linker out)
  foreach(_n IN LISTS ARGN)
    find_program(_p NAMES "${_n}")
    if(_p)
      set(${out} "${_p}" PARENT_SCOPE)
      unset(_p CACHE)
      return()
    endif()
    unset(_p CACHE)
  endforeach()
  set(${out} "" PARENT_SCOPE)
endfunction()

function(xsigma_print_lto_linker_summary prefix)
  set(_m "${${prefix}_LTO_MODE}")
  if(NOT DEFINED ${prefix}_LINKER_CHOICE)
    set(_link "default")
  else()
    set(_link "${${prefix}_LINKER_CHOICE}")
  endif()
  string(TOLOWER "${_m}" _low)
  set(_hint "")
  if(_low STREQUAL "auto")
    _xsigma_msvc_link(_w)
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND NOT _w)
      set(_hint " → thin")
    else()
      set(_hint " → ipo")
    endif()
  endif()
  set(_skip "")
  if(${prefix}_ENABLE_COVERAGE OR ${prefix}_ENABLE_SANITIZER)
    set(_skip " (skipped: coverage/sanitizer)")
  endif()
  message("  LTO mode             : ${_m}${_hint}${_skip}")
  message("  Linker choice        : ${_link}")
endfunction()

function(xsigma_lto_compute_default out_var)
  cmake_parse_arguments(_ql "" "PROFILE" "" ${ARGN})
  if(NOT _ql_PROFILE)
    set(_ql_PROFILE "PERFORMANCE")
  endif()
  if(_ql_PROFILE STREQUAL "SUPPORT")
    set(${out_var} "off" PARENT_SCOPE)
    return()
  endif()
  if(NOT CMAKE_BUILD_TYPE)
    set(${out_var} "off" PARENT_SCOPE)
    return()
  endif()
  string(TOUPPER "${CMAKE_BUILD_TYPE}" _bt)
  if(_bt STREQUAL "DEBUG")
    set(${out_var} "off" PARENT_SCOPE)
    return()
  endif()
  set(${out_var} "auto" PARENT_SCOPE)
endfunction()

function(xsigma_target_apply_lto target prefix)
  set(_m "${${prefix}_LTO_MODE}")
  string(TOLOWER "${_m}" _m)
  if(_m STREQUAL "" OR _m STREQUAL "off")
    message(STATUS "${target}: LTO off")
    return()
  endif()
  if(${prefix}_ENABLE_COVERAGE OR ${prefix}_ENABLE_SANITIZER)
    message(STATUS "${target}: LTO skipped (coverage/sanitizer)")
    return()
  endif()
  get_target_property(_launch "${target}" RULE_LAUNCH_COMPILE)
  if(_launch MATCHES "sccache")
    message(
      FATAL_ERROR
        "${target}: LTO incompatible with sccache — set ${prefix}_CACHE_BACKEND=none or LTO off"
    )
  endif()

  _xsigma_msvc_link(_msvc)
  if(_m STREQUAL "auto")
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" AND NOT _msvc)
      set(_m "thin")
    else()
      set(_m "ipo")
    endif()
  endif()

  if(_m STREQUAL "thin")
    # -flto=thin emits bitcode; default try_compile links with bfd and fails — use static lib probe.
    set(_save_try "${CMAKE_TRY_COMPILE_TARGET_TYPE}")
    set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
    check_cxx_compiler_flag("-flto=thin" _ok)
    set(CMAKE_TRY_COMPILE_TARGET_TYPE "${_save_try}")
    set(_flag "-flto=thin")
    if(NOT _ok AND _msvc)
      set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
      check_cxx_compiler_flag("/clang:-flto=thin" _ok2)
      set(CMAKE_TRY_COMPILE_TARGET_TYPE "${_save_try}")
      if(_ok2)
        set(_flag "/clang:-flto=thin")
        set(_ok TRUE)
      endif()
    endif()
    if(_ok)
      target_compile_options("${target}" PRIVATE "${_flag}")
      target_link_options("${target}" PRIVATE "${_flag}")
      message(STATUS "${target}: ThinLTO (${_flag})")
      return()
    endif()
    message(WARNING "${target}: ThinLTO unsupported — trying IPO")
    set(_m "ipo")
  endif()

  if(_m STREQUAL "full")
    if(MSVC AND NOT CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      target_compile_options("${target}" PRIVATE /GL)
      target_link_options("${target}" PRIVATE /LTCG)
      message(STATUS "${target}: LTO (/GL /LTCG)")
      return()
    endif()
    check_cxx_compiler_flag("-flto" _fok)
    if(_fok)
      target_compile_options("${target}" PRIVATE -flto)
      target_link_options("${target}" PRIVATE -flto)
      message(STATUS "${target}: LTO (-flto)")
      return()
    endif()
    message(WARNING "${target}: -flto unsupported — trying IPO")
    set(_m "ipo")
  endif()

  if(_m STREQUAL "ipo")
    check_ipo_supported(RESULT _iok OUTPUT _ierr LANGUAGES CXX)
    if(_iok)
      set_target_properties("${target}" PROPERTIES INTERPROCEDURAL_OPTIMIZATION ON)
      message(STATUS "${target}: IPO/LTO")
    else()
      message(WARNING "${target}: IPO unsupported: ${_ierr}")
    endif()
    return()
  endif()

  message(WARNING "${target}: unknown LTO mode '${${prefix}_LTO_MODE}'")
endfunction()

function(_xsigma_apply_fuse target path)
  if(NOT path OR NOT TARGET "${target}")
    return()
  endif()
  _xsigma_msvc_link(_msvc)
  if(CMAKE_SYSTEM_NAME STREQUAL "Windows" AND CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND _msvc)
    return()
  endif()
  if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
    get_filename_component(_b "${path}" NAME)
    string(REGEX REPLACE "\\.exe$" "" _s "${_b}")
    string(REPLACE "ld." "" _s "${_s}")
    target_link_options("${target}" PUBLIC "-fuse-ld=${_s}")
    message(STATUS "Linker: ${target} → -fuse-ld=${_s}")
  elseif(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC" AND path MATCHES "lld-link")
    set(CMAKE_LINKER "${path}" CACHE FILEPATH "Linker")
    message(STATUS "Linker: ${path}")
  endif()
endfunction()

# Resolve linker: lto_on picks LLVM-friendly order for Clang; otherwise speed-first order.
function(_xsigma_pick_link linker_choice target lto_on)
  set(_path "")
  if(NOT linker_choice STREQUAL "default")
    find_program(_e NAMES "${linker_choice}" "ld.${linker_choice}" "${linker_choice}-link")
    if(_e)
      set(_path "${_e}")
      message(STATUS "Linker: explicit '${linker_choice}'")
    else()
      message(WARNING "Linker: '${linker_choice}' not found — auto")
    endif()
    unset(_e CACHE)
  endif()

  if(_path)
    _xsigma_apply_fuse("${target}" "${_path}")
    return()
  endif()

  _xsigma_msvc_link(_msvc)
  if(_msvc OR CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
    return()
  endif()

  if(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    _xsigma_first_linker(_path ld64.lld)
    if(_path)
      _xsigma_apply_fuse("${target}" "${_path}")
    elseif(NOT lto_on)
      message(STATUS "Linker: macOS system ld64")
    else()
      message(STATUS "Linker: macOS ld64 (LTO-capable)")
    endif()
    return()
  endif()

  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
      if(lto_on)
        _xsigma_first_linker(_path ld.lld mold ld.gold)
      else()
        _xsigma_first_linker(_path mold ld.gold ld.lld)
      endif()
    elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
      _xsigma_first_linker(_path mold ld.gold ld.lld)
    endif()
    if(_path)
      _xsigma_apply_fuse("${target}" "${_path}")
    elseif(lto_on)
      message(WARNING "Linker: install ld.lld, mold, or gold for LTO")
    else()
      message(STATUS "Linker: platform default")
    endif()
    return()
  endif()

  if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    if(CMAKE_CXX_COMPILER_ID MATCHES "Clang" OR CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
      _xsigma_first_linker(_path ld.lld lld)
      if(_path)
        _xsigma_apply_fuse("${target}" "${_path}")
      endif()
    endif()
  endif()
endfunction()

function(xsigma_find_linker linker_choice target_name)
  set(_lto FALSE)
  if(CMAKE_INTERPROCEDURAL_OPTIMIZATION OR "$CACHE{CMAKE_INTERPROCEDURAL_OPTIMIZATION}")
    set(_lto TRUE)
  endif()
  if(NOT _lto AND ARGC GREATER 2)
    set(_mv "${ARGV2}")
    if(DEFINED "${_mv}")
      string(TOLOWER "${${_mv}}" _v)
      if(NOT _v STREQUAL "off" AND NOT _v STREQUAL "")
        set(_lto TRUE)
      endif()
    endif()
  endif()
  _xsigma_pick_link("${linker_choice}" "${target_name}" ${_lto})
endfunction()
