# =============================================================================
# XSigma
# Configuration Summary Module
#
# print_configuration_summary — workspace-wide toolchain and CMake metadata only. Per-library CMake
# flag summaries live at the end of each Library/*/CMakeLists.txt.
# =============================================================================
# include_guard(GLOBAL)

function(print_configuration_summary)
  message("")
  message("******** Global build summary ********")
  message("Toolchain:")
  message("  CMake version            : ${CMAKE_VERSION}")
  message("  CMake command            : ${CMAKE_COMMAND}")
  message("  CMake generator          : ${CMAKE_GENERATOR}")
  message("  CMake build tool         : ${CMAKE_BUILD_TOOL}")
  message("  System                   : ${CMAKE_SYSTEM_NAME}")
  message("  C compiler               : ${CMAKE_C_COMPILER}")
  message("  C compiler id            : ${CMAKE_C_COMPILER_ID}")
  message("  C compiler version       : ${CMAKE_C_COMPILER_VERSION}")
  message("  C++ compiler             : ${CMAKE_CXX_COMPILER}")
  message("  C++ compiler id          : ${CMAKE_CXX_COMPILER_ID}")
  message("  C++ compiler version     : ${CMAKE_CXX_COMPILER_VERSION}")
  message("Paths:")
  message("  CMAKE_PREFIX_PATH        : ${CMAKE_PREFIX_PATH}")
  message("  CMAKE_INSTALL_PREFIX     : ${CMAKE_INSTALL_PREFIX}")
  message("  PROJECT_SOURCE_DIR       : ${PROJECT_SOURCE_DIR}")
  message("  PROJECT_BINARY_DIR       : ${PROJECT_BINARY_DIR}")
  message("  PROJECT_VERSION          : ${PROJECT_VERSION}")
  if(DEFINED CMAKE_BUILD_OPTIONS)
    message("  CMAKE_BUILD_OPTIONS      : ${CMAKE_BUILD_OPTIONS}")
  endif()
  if(DEFINED CMAKE_BUILD_FLAGS)
    message("  CMAKE_BUILD_FLAGS        : ${CMAKE_BUILD_FLAGS}")
  endif()
  if(DEFINED PROJECT_DLL_PATHS)
    message("  PROJECT_DLL_PATHS        : ${PROJECT_DLL_PATHS}")
  endif()
  if(DEFINED PROJECT_DATA_STORE)
    message("  PROJECT_DATA_STORE       : ${PROJECT_DATA_STORE}")
  endif()
  message("Options:")
  message("  BUILD_SHARED_LIBS        : ${BUILD_SHARED_LIBS}")
  message("  XSIGMA_ENABLE_EXTERNAL : ${XSIGMA_ENABLE_EXTERNAL}")
  if(DEFINED XSIGMA_LIBRARY_PROJECT AND NOT XSIGMA_LIBRARY_PROJECT STREQUAL "")
    message("  XSIGMA_LIBRARY_PROJECT : ${XSIGMA_LIBRARY_PROJECT}")
  endif()
  message("")
endfunction()
